const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, AlignmentType, ShadingType, BorderStyle, HeadingLevel } = require('docx');

// ─── Excel Export ────────────────────────────────────────────────────────────
async function exportExcel(statements, notes, meta) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'FinStatement Generator';
  wb.created = new Date();

  const { entity_name, period_end, currency } = meta;

  addCoverSheet(wb, entity_name, period_end, currency);
  addBSSheet(wb, statements.balance_sheet, entity_name, period_end, currency);
  addISSheet(wb, statements.income_statement, entity_name, period_end, currency);
  addCFSheet(wb, statements.cash_flow, entity_name, period_end, currency);
  addEqSheet(wb, statements.equity_statement, entity_name, period_end, currency);
  addNotesSheet(wb, notes);

  return wb.xlsx.writeBuffer();
}

const BLUE  = 'FF1557A0';
const LBLUE = 'FFDBEAFE';
const LGRAY = 'FFF8FAFC';
const DGRAY = 'FF334155';
const GREEN = 'FF16A34A';
const RED   = 'FFDC2626';
const WHITE = 'FFFFFFFF';
const BORDER_THIN = { style: 'thin', color: { argb: 'FFE2E8F0' } };

function styleHeader(ws, row, col, value, opts = {}) {
  const cell = ws.getCell(row, col);
  cell.value = value;
  cell.font  = { bold: true, color: { argb: WHITE }, size: opts.size || 11 };
  cell.fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: opts.bg || BLUE } };
  cell.alignment = { horizontal: opts.align || 'left', vertical: 'middle' };
}

function fmtNum(v) { return Number(v || 0); }

function numCell(ws, row, col, val, bold = false, colorArgb = null) {
  const cell = ws.getCell(row, col);
  cell.value  = fmtNum(val);
  cell.numFmt = '#,##0.00;[Red](#,##0.00)';
  cell.alignment = { horizontal: 'right' };
  cell.font = { bold, color: colorArgb ? { argb: colorArgb } : undefined };
}

function addCoverSheet(wb, entity, period, currency) {
  const ws = wb.addWorksheet('Cover');
  ws.getColumn(1).width = 60;
  ws.mergeCells('A1:A3');
  const title = ws.getCell('A1');
  title.value = entity || 'Financial Statements';
  title.font  = { bold: true, size: 20, color: { argb: BLUE } };
  title.alignment = { vertical: 'middle' };
  ws.getCell('A4').value = `Period ended: ${period || ''}`;
  ws.getCell('A4').font  = { size: 12, color: { argb: DGRAY } };
  ws.getCell('A5').value = `Currency: ${currency || 'USD'}`;
  ws.getCell('A5').font  = { size: 11, color: { argb: DGRAY } };
  ws.getCell('A7').value = 'Generated by Financial Statement Generator';
  ws.getCell('A7').font  = { size: 10, color: { argb: '99999999' }, italic: true };
  const contents = ['Balance Sheet','Income Statement','Cash Flow Statement','Changes in Equity','Notes'];
  ws.getCell('A9').value = 'Contents';
  ws.getCell('A9').font  = { bold: true, size: 12 };
  contents.forEach((c, i) => { ws.getCell(`A${10 + i}`).value = `  ${i + 1}. ${c}`; });
}

function initSheet(wb, name, entity, period, currency) {
  const ws = wb.addWorksheet(name);
  ws.getColumn(1).width = 42;
  ws.getColumn(2).width = 18;
  ws.getColumn(3).width = 18;
  let r = 1;
  ws.mergeCells(`A${r}:C${r}`); styleHeader(ws, r, 1, entity || 'Company', { size: 14 }); r++;
  ws.mergeCells(`A${r}:C${r}`); styleHeader(ws, r, 1, name, { size: 12 }); r++;
  ws.mergeCells(`A${r}:C${r}`); styleHeader(ws, r, 1, `Period ended: ${period || ''}`, { size: 10, bg: '334155' }); r += 2;
  styleHeader(ws, r, 1, 'Description', { bg: BLUE });
  styleHeader(ws, r, 2, currency || 'USD', { bg: BLUE, align: 'right' });
  styleHeader(ws, r, 3, 'Total', { bg: BLUE, align: 'right' });
  r++;
  return { ws, r };
}

// Render a dict-based sections object: { 'Category': { items: [{label,amount}], total } }
// categoryOrder controls the display order
function renderDictSections(ws, sectionsDict, startRow, categoryOrder) {
  let r = startRow;
  const keys = categoryOrder
    ? [...categoryOrder.filter(k => sectionsDict[k]), ...Object.keys(sectionsDict).filter(k => !categoryOrder.includes(k))]
    : Object.keys(sectionsDict);

  for (const cat of keys) {
    const sec = sectionsDict[cat];
    if (!sec) continue;

    // Section header
    const secCell = ws.getCell(r, 1);
    secCell.value = cat;
    secCell.font  = { bold: true, color: { argb: WHITE }, size: 11 };
    secCell.fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: BLUE } };
    ws.mergeCells(`A${r}:C${r}`);
    r++;

    for (const item of (sec.items || [])) {
      ws.getCell(r, 1).value = `  ${item.label}`;
      ws.getCell(r, 1).font  = { size: 10, color: { argb: DGRAY } };
      numCell(ws, r, 2, item.amount);
      r++;
    }

    // Section total
    ws.getCell(r, 1).value = `Total ${cat}`;
    ws.getCell(r, 1).font  = { bold: true };
    ws.getCell(r, 1).fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: LBLUE } };
    numCell(ws, r, 3, sec.total, true, BLUE);
    ws.getCell(r, 3).fill   = { type: 'pattern', pattern: 'solid', fgColor: { argb: LBLUE } };
    ws.getCell(r, 3).border = { top: { style: 'medium', color: { argb: BLUE } }, bottom: { style: 'double', color: { argb: BLUE } } };
    r += 2;
  }
  return r;
}

function addGrandRow(ws, r, label, value) {
  ws.getCell(r, 1).value = label;
  ws.getCell(r, 1).font  = { bold: true, size: 11, color: { argb: WHITE } };
  ws.getCell(r, 1).fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: BLUE } };
  numCell(ws, r, 3, value, true, WHITE);
  ws.getCell(r, 3).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BLUE } };
}

function addBSSheet(wb, bs, entity, period, currency) {
  const { ws, r: startRow } = initSheet(wb, 'Balance Sheet', entity, period, currency);
  const order = ['Current Assets','Non-Current Assets','Current Liabilities','Non-Current Liabilities','Equity'];
  let r = renderDictSections(ws, bs?.sections || {}, startRow, order);
  addGrandRow(ws, r,   'TOTAL ASSETS', bs?.total_assets); r++;
  addGrandRow(ws, r,   'TOTAL LIABILITIES AND EQUITY', bs?.total_liabilities_and_equity);
}

function addISSheet(wb, is, entity, period, currency) {
  const { ws, r: startRow } = initSheet(wb, 'Income Statement', entity, period, currency);
  const order = ['Revenue','Cost of Sales','Operating Expenses','Finance Costs','Income Tax'];
  let r = renderDictSections(ws, is?.sections || {}, startRow, order);

  [
    ['Gross Profit',             is?.gross_profit, GREEN],
    ['Operating Profit (EBIT)',  is?.ebit,         BLUE],
    ['Profit Before Tax',        is?.ebt,          BLUE],
    ['Net Income / (Loss)',      is?.net_income,   (is?.net_income ?? 0) >= 0 ? GREEN : RED],
  ].forEach(([label, val, col]) => {
    addGrandRow(ws, r, label, val);
    ws.getCell(r, 1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: col } };
    ws.getCell(r, 3).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: col } };
    r++;
  });
}

function addCFSheet(wb, cf, entity, period, currency) {
  const { ws, r: startRow } = initSheet(wb, 'Cash Flow', entity, period, currency);
  const order = ['Operating Activities','Investing Activities','Financing Activities'];
  let r = renderDictSections(ws, cf?.sections || {}, startRow, order);
  addGrandRow(ws, r, 'NET CHANGE IN CASH', cf?.net_change_in_cash);
}

function addEqSheet(wb, eq, entity, period, currency) {
  const { ws, r } = initSheet(wb, 'Changes in Equity', entity, period, currency);
  if (!eq) return;
  let row = r;
  const items = [
    ['Opening Equity',             eq.opening_equity],
    ['Net Income for the Period',  eq.net_income],
    ['Dividends Declared',        -Math.abs(eq.dividends || 0)],
    ['Other Movements',            eq.other_movements],
  ];
  for (const [label, val] of items) {
    ws.getCell(row, 1).value = `  ${label}`;
    numCell(ws, row, 2, val);
    row++;
  }
  addGrandRow(ws, row, 'CLOSING EQUITY', eq.closing_equity);
}

function addNotesSheet(wb, notes) {
  const ws = wb.addWorksheet('Notes');
  ws.getColumn(1).width = 100;
  styleHeader(ws, 1, 1, 'Notes to the Financial Statements', { size: 14 });
  let r = 3;
  for (const note of (notes || [])) {
    ws.getCell(r, 1).value = note.title;
    ws.getCell(r, 1).font  = { bold: true, size: 12, color: { argb: BLUE } };
    r++;
    const text = (note.content || '')
      .replace(/<[^>]+>/g, '')
      .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&nbsp;/g, ' ');
    ws.getCell(r, 1).value = text;
    ws.getCell(r, 1).alignment = { wrapText: true };
    ws.getRow(r).height = Math.min(200, Math.max(30, text.length / 2));
    r += 2;
  }
}

// ─── PDF Export ──────────────────────────────────────────────────────────────
async function exportPDF(statements, notes, meta) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', d => chunks.push(d));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const { entity_name, period_end, currency } = meta;
    const fmt = n => Number(n || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    const pageWidth = doc.page.width - 100;

    doc.fontSize(22).fillColor('#1557a0').text(entity_name || 'Financial Statements', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor('#334155').text('Financial Statements', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('#64748b').text(`Period ended: ${period_end || ''}  |  Currency: ${currency || 'USD'}`, { align: 'center' });
    doc.moveDown(2);

    const sectionHeader = (title) => {
      doc.addPage();
      doc.fontSize(14).fillColor('#1557a0').text(title);
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).strokeColor('#1557a0').lineWidth(2).stroke();
      doc.moveDown(0.5);
    };

    const dataRow = (label, amount, bold = false, indent = 0) => {
      const y = doc.y;
      doc.font(bold ? 'Helvetica-Bold' : 'Helvetica')
        .fontSize(9).fillColor(bold ? '#1557a0' : '#1a2332')
        .text(' '.repeat(indent) + label, 50, y, { width: pageWidth - 80, continued: false });
      if (amount !== undefined && amount !== '') {
        doc.font(bold ? 'Helvetica-Bold' : 'Helvetica')
          .fontSize(9).fillColor(bold ? '#1557a0' : '#1a2332')
          .text(fmt(amount), 50 + pageWidth - 80, y, { width: 80, align: 'right' });
      }
    };

    const renderSections = (sectionsDict, categoryOrder) => {
      if (!sectionsDict) return;
      const keys = categoryOrder
        ? [...categoryOrder.filter(k => sectionsDict[k]), ...Object.keys(sectionsDict).filter(k => !categoryOrder.includes(k))]
        : Object.keys(sectionsDict);

      for (const cat of keys) {
        const sec = sectionsDict[cat];
        if (!sec) continue;
        doc.font('Helvetica-Bold').fontSize(10);
        doc.rect(50, doc.y, pageWidth, 16).fill('#1557a0');
        doc.fillColor('#ffffff').text(cat, 54, doc.y - 13, { width: pageWidth - 8 });
        doc.moveDown(0.3);
        for (const item of (sec.items || [])) {
          dataRow(item.label, item.amount, false, 4);
        }
        dataRow(`Total ${cat}`, sec.total, true, 2);
        doc.moveDown(0.3);
      }
    };

    // Balance Sheet
    sectionHeader('Statement of Financial Position (Balance Sheet)');
    renderSections(statements.balance_sheet?.sections, ['Current Assets','Non-Current Assets','Current Liabilities','Non-Current Liabilities','Equity']);
    doc.moveDown(0.5);
    dataRow('TOTAL ASSETS', statements.balance_sheet?.total_assets, true);
    dataRow('TOTAL LIABILITIES AND EQUITY', statements.balance_sheet?.total_liabilities_and_equity, true);

    // Income Statement
    sectionHeader('Statement of Profit or Loss (Income Statement)');
    renderSections(statements.income_statement?.sections, ['Revenue','Cost of Sales','Operating Expenses','Finance Costs','Income Tax']);
    doc.moveDown(0.5);
    dataRow('Gross Profit',  statements.income_statement?.gross_profit, true);
    dataRow('Net Income',    statements.income_statement?.net_income,   true);

    // Cash Flow
    sectionHeader('Statement of Cash Flows');
    renderSections(statements.cash_flow?.sections, ['Operating Activities','Investing Activities','Financing Activities']);
    dataRow('NET CHANGE IN CASH', statements.cash_flow?.net_change_in_cash, true);

    // Changes in Equity
    sectionHeader('Statement of Changes in Equity');
    const eq = statements.equity_statement;
    if (eq) {
      dataRow('Opening Equity',            eq.opening_equity,            false, 4);
      dataRow('Net Income for the Period', eq.net_income,                false, 4);
      dataRow('Dividends Declared',        -Math.abs(eq.dividends || 0), false, 4);
      dataRow('Other Movements',           eq.other_movements,           false, 4);
      dataRow('CLOSING EQUITY',            eq.closing_equity,            true);
    }

    // Notes
    if (notes?.length) {
      doc.addPage();
      doc.fontSize(14).fillColor('#1557a0').text('Notes to the Financial Statements');
      doc.moveDown(1);
      for (const note of notes) {
        doc.font('Helvetica-Bold').fontSize(11).fillColor('#1557a0').text(note.title);
        doc.moveDown(0.3);
        const text = (note.content || '').replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ');
        doc.font('Helvetica').fontSize(9).fillColor('#1a2332').text(text, { width: pageWidth });
        doc.moveDown(0.8);
      }
    }

    doc.end();
  });
}

// ─── Word Export ─────────────────────────────────────────────────────────────
async function exportWord(statements, notes, meta) {
  const { entity_name, period_end, currency } = meta;
  const fmt = n => Number(n || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const blueShading = { type: ShadingType.SOLID, color: '1557a0', fill: '1557a0' };
  const lblueShading = { type: ShadingType.SOLID, color: 'dbeafe', fill: 'dbeafe' };

  function makeCell(text, opts = {}) {
    return new TableCell({
      shading: opts.shading,
      width: opts.width ? { size: opts.width, type: WidthType.PERCENTAGE } : undefined,
      children: [new Paragraph({
        alignment: opts.right ? AlignmentType.RIGHT : AlignmentType.LEFT,
        children: [new TextRun({
          text: String(text ?? ''),
          bold: !!opts.bold,
          color: opts.white ? 'FFFFFF' : opts.color || '1a2332',
          size: opts.size || 20,
        })],
      })],
    });
  }

  function sectionRows(sectionsDict, categoryOrder) {
    if (!sectionsDict) return [];
    const rows = [];
    const keys = categoryOrder
      ? [...categoryOrder.filter(k => sectionsDict[k]), ...Object.keys(sectionsDict).filter(k => !categoryOrder.includes(k))]
      : Object.keys(sectionsDict);

    for (const cat of keys) {
      const sec = sectionsDict[cat];
      if (!sec) continue;
      // category header row
      rows.push(new TableRow({ children: [
        makeCell(cat, { bold: true, white: true, shading: blueShading, width: 60 }),
        makeCell('', { shading: blueShading, width: 20 }),
        makeCell('', { shading: blueShading, width: 20 }),
      ]}));
      for (const item of (sec.items || [])) {
        rows.push(new TableRow({ children: [
          makeCell(`    ${item.label}`, { width: 60 }),
          makeCell(fmt(item.amount), { right: true, width: 20 }),
          makeCell('', { width: 20 }),
        ]}));
      }
      rows.push(new TableRow({ children: [
        makeCell(`Total ${cat}`, { bold: true, shading: lblueShading, width: 60 }),
        makeCell('', { shading: lblueShading, width: 20 }),
        makeCell(fmt(sec.total), { bold: true, right: true, color: '1557a0', shading: lblueShading, width: 20 }),
      ]}));
    }
    return rows;
  }

  function grandRow(label, value) {
    return new TableRow({ children: [
      makeCell(label, { bold: true, white: true, shading: blueShading, width: 60 }),
      makeCell('', { shading: blueShading, width: 20 }),
      makeCell(fmt(value), { bold: true, right: true, white: true, shading: blueShading, width: 20 }),
    ]});
  }

  function heading(text) {
    return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text, color: '1557a0', bold: true })] });
  }

  function makeTable(rows) {
    return new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({ children: [
          makeCell('Description', { bold: true, white: true, shading: blueShading, width: 60 }),
          makeCell(currency || 'USD', { bold: true, right: true, white: true, shading: blueShading, width: 20 }),
          makeCell('Total', { bold: true, right: true, white: true, shading: blueShading, width: 20 }),
        ]}),
        ...rows,
      ],
    });
  }

  const bs = statements.balance_sheet;
  const is = statements.income_statement;
  const cf = statements.cash_flow;
  const eq = statements.equity_statement;

  const bsRows = [
    ...sectionRows(bs?.sections, ['Current Assets','Non-Current Assets','Current Liabilities','Non-Current Liabilities','Equity']),
    grandRow('TOTAL ASSETS', bs?.total_assets),
    grandRow('TOTAL LIABILITIES AND EQUITY', bs?.total_liabilities_and_equity),
  ];
  const isRows = [
    ...sectionRows(is?.sections, ['Revenue','Cost of Sales','Operating Expenses','Finance Costs','Income Tax']),
    grandRow('GROSS PROFIT', is?.gross_profit),
    grandRow('NET INCOME / (LOSS)', is?.net_income),
  ];
  const cfRows = [
    ...sectionRows(cf?.sections, ['Operating Activities','Investing Activities','Financing Activities']),
    grandRow('NET CHANGE IN CASH', cf?.net_change_in_cash),
  ];
  const eqRows = eq ? [
    new TableRow({ children: [makeCell('Opening Equity', { width: 60 }), makeCell(fmt(eq.opening_equity), { right: true, width: 20 }), makeCell('', { width: 20 })] }),
    new TableRow({ children: [makeCell('Net Income for the Period', { width: 60 }), makeCell(fmt(eq.net_income), { right: true, width: 20 }), makeCell('', { width: 20 })] }),
    new TableRow({ children: [makeCell('Dividends Declared', { width: 60 }), makeCell(fmt(-Math.abs(eq.dividends || 0)), { right: true, width: 20 }), makeCell('', { width: 20 })] }),
    new TableRow({ children: [makeCell('Other Movements', { width: 60 }), makeCell(fmt(eq.other_movements || 0), { right: true, width: 20 }), makeCell('', { width: 20 })] }),
    grandRow('CLOSING EQUITY', eq.closing_equity),
  ] : [];

  const notesParagraphs = (notes || []).flatMap(note => [
    new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: note.title, color: '1557a0', bold: true })] }),
    new Paragraph({ children: [new TextRun({
      text: (note.content || '').replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').trim(),
      size: 18,
    })] }),
    new Paragraph({ children: [] }),
  ]);

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: entity_name || 'Financial Statements', color: '1557a0', bold: true, size: 36 })] }),
        new Paragraph({ children: [new TextRun({ text: `Period ended: ${period_end || ''}  |  Currency: ${currency || 'USD'}`, color: '64748b' })] }),
        new Paragraph({ children: [] }),

        heading('Statement of Financial Position (Balance Sheet)'),
        makeTable(bsRows),
        new Paragraph({ children: [] }),

        heading('Statement of Profit or Loss (Income Statement)'),
        makeTable(isRows),
        new Paragraph({ children: [] }),

        heading('Statement of Cash Flows'),
        makeTable(cfRows),
        new Paragraph({ children: [] }),

        heading('Statement of Changes in Equity'),
        makeTable(eqRows),
        new Paragraph({ children: [] }),

        heading('Notes to the Financial Statements'),
        ...notesParagraphs,
      ],
    }],
  });

  return Packer.toBuffer(doc);
}

module.exports = { exportExcel, exportPDF, exportWord };
